### ISSUE TITLE
MW2CR Crashes

### ISSUE THREAD

**Issue by V3nilla** [fedddddd/h2-mod#111]
MW2CR just crashes with 0xc000005 error code(EXCEPTION_ACCESS_VIOLATION)

Using:
Latest available repo .exe
Latest available game cracks(i dont have money lol) - Extern, ExternV1, ExternV2, ExternV3, Razor1911

**Comment by fedddddd** [comment]
Post the crash dump

**Comment by V3nilla** [comment]
[h2-mod-crash-1-2021-12-30-15-14-09.zip](https://github.com/fedddddd/h2-mod/files/7792684/h2-mod-crash-1-2021-12-30-15-14-09.zip)

**Comment by fedddddd** [comment]
Your cracked game binary is not compatible, try [this one](https://drive.google.com/file/d/191MEoBF9-EvZbRXLA2gK1-Yxs2YnULjj/view?usp=sharing)

**Comment by V3nilla** [comment]
Now it works! Thank you!

**Comment by illnyang** [comment]
@fedddddd it wouldn't hurt to delta patch all of the mentioned crack releases into the correct one, that's what open-iw5 does (delta ratio is another story; it's mostly just to avoid storing plain copyrighted EXEs on this repo). zstd supports delta patching since recently.

**Comment by fedddddd** [comment]
Actually the game can be installed for free with [Battle.Net Installer](https://github.com/barncastle/Battle.Net-Installer):
```
.\bnetinstaller.exe --prod lazr --uid lazarus --lang enUS --dir "YOUR INSTALL PATH"
```
So just use this instead (of course replace "YOUR INSTALL PATH" with your actual path, same goes for the language).

**Comment by illnyang** [comment]
@fedddddd that's even better, thanks for the tip. consider adding that info in the README

**Comment by Anma5064** [comment]
Pirated crash error unsupported Call of Duty - MW2 Campaign Remastered version

**Comment by Anma5064** [comment]
tutorial fix

**Comment by skkuull** [comment]
> tutorial fix

BRO fed just explained above how to get the game files for free, https://github.com/fedddddd/h2-mod/issues/111#issuecomment-1109880013
