### ISSUE TITLE
New built-in Injector faulty

### ISSUE THREAD

**Issue by hosseinpourziyaie** [fedddddd/h2-mod#19]
btw crash happense after hitting SP start btn
![bandicam 2021-09-09 13-26-29-619](https://user-images.githubusercontent.com/22142481/132656291-1e312542-88e2-4f23-9be3-bed70fc0ccbc.jpg)
[h2-mod-crash-1-2021-09-09-13-24-30.zip](https://github.com/fedddddd/h2-mod/files/7135089/h2-mod-crash-1-2021-09-09-13-24-30.zip)

**Comment by fedddddd** [comment]
You aren't running the latest version of h2-mod, download it from the readme

**Comment by hosseinpourziyaie** [comment]
still same happens

![bandicam 2021-09-09 15-28-37-352](https://user-images.githubusercontent.com/22142481/132674118-0a275e99-9bff-48ba-ad0e-b5969cb62ee9.jpg)

**Comment by fedddddd** [comment]
Send the minidump please

**Comment by hosseinpourziyaie** [comment]
[h2-mod-crash-1-2021-09-09-15-22-09.zip](https://github.com/fedddddd/h2-mod/files/7136048/h2-mod-crash-1-2021-09-09-15-22-09.zip)

**Comment by fedddddd** [comment]
Actually use this binary & upload the minidump
[h2-mod.zip](https://github.com/fedddddd/h2-mod/files/7136148/h2-mod.zip)

**Comment by hosseinpourziyaie** [comment]
[h2-mod-crash-1-2021-09-09-16-07-35.zip](https://github.com/fedddddd/h2-mod/files/7136169/h2-mod-crash-1-2021-09-09-16-07-35.zip)
there you are; btw if you want I can send process dump too,
or you could just connect using anydesk as I have all debuging tools

**Comment by fedddddd** [comment]
That won't be necessary, from the screenshot I think your game is outdated, upload your MW2CR.exe

**Comment by hosseinpourziyaie** [comment]
can you provide your runtime binary for me as I already removed battle.net and dont have access to it anymore

**Comment by fedddddd** [comment]
[MW2CR.zip](https://github.com/fedddddd/h2-mod/files/7139673/MW2CR.zip)

**Comment by hosseinpourziyaie** [comment]
Thanks for the help

https://github.com/hosseinpourziyaie/H2MOD_SCRIPTS/tree/main/cinematic_flight

Enjoy! 

P.S: dm me on discord if you can; i just left a message on iw6x-modding  channel with a profile similar to this

**Comment by fedddddd** [comment]
I'm not in that discord but you can add me: fed#0001. Also the game has something similar built in, it can be enabled by doing `set beautiful_corner_demo 1`
