### ISSUE TITLE
English only access

### ISSUE THREAD

**Issue by liveskai** [fedddddd/h2-mod#298]
Can't support other languages?

**Comment by fedddddd** [comment]
It supports whatever language you downloaded the game in

**Comment by liveskai** [comment]
> 它支持您下载游戏的任何语言


My game is launched from Battle.net in Chinese
But with H2MOD it starts in English
If I launch with H2MOD, it is in Chinese

**Comment by VladWinner** [comment]
@liveskai https://github.com/fedddddd/h2-mod/issues/111#issuecomment-1109880013
Just change enUS with zhCN

**Comment by fedddddd** [comment]
> @liveskai [#111 (comment)](https://github.com/fedddddd/h2-mod/issues/111#issuecomment-1109880013) Try change `--lang enUS` with `--lang zhCN` [(source)](https://github.com/barncastle/Battle.Net-Installer/blob/master/BNetInstaller/Constants/Locale.cs)

The game is shipped with all languages, it uses the language set by the bnet launcher or your system's language, if it fails it just defaults to english. f1563dc0e67ea1f511a288ed17dd99a83711ee55 allows to manually select the language ingame.

**Comment by liveskai** [comment]
> > @liveskai [#111（评论）](https://github.com/fedddddd/h2-mod/issues/111#issuecomment-1109880013)尝试改变`--lang enUS`（`--lang zhCN` [来源）](https://github.com/barncastle/Battle.Net-Installer/blob/master/BNetInstaller/Constants/Locale.cs)
> 
> 游戏附带所有语言，它使用 bnet 启动器设置的语言或您系统的语言，如果失败则默认为英语。[f1563dc](https://github.com/fedddddd/h2-mod/commit/f1563dc0e67ea1f511a288ed17dd99a83711ee55)允许手动选择游戏语言。
I can't read it

**Comment by liveskai** [comment]
> > @liveskai [#111 (comment)](https://github.com/fedddddd/h2-mod/issues/111#issuecomment-1109880013) Try change `--lang enUS` with `--lang zhCN` [(source)](https://github.com/barncastle/Battle.Net-Installer/blob/master/BNetInstaller/Constants/Locale.cs)
> 
> The game is shipped with all languages, it uses the language set by the bnet launcher or your system's language, if it fails it just defaults to english. [f1563dc](https://github.com/fedddddd/h2-mod/commit/f1563dc0e67ea1f511a288ed17dd99a83711ee55) allows to manually select the language ingame.

I can't read it
