### ISSUE TITLE
Unsupported characters in the console

### ISSUE THREAD

**Issue by VladWinner** [fedddddd/h2-mod#302]
h2-mod.exe 'is not responding' when I start typing unsupported characters (e.g. `ф`) into the console. The game freezes, but the music and sounds keep playing. I don't know what this is related to, but there is no hanging in H1-Mod.

**Comment by fedddddd** [comment]
Not sure how this would happen since the console input only allows chars from 0-127 and copy-pasting the character just prints '?'. The freezing can happen on h1-mod as well with certain characters

**Comment by VladWinner** [comment]
Hurray, I found the culprit. This is a very rare case and isn’t directly related to the console input.
`h2-mod.exe` hang after receive a Win32API message `WM_INPUTLANGCHANGEREQUEST`.
#### Workaround: just add `h2-mod.exe` to exception list of used keyboard layout manager.

**Comment by VladWinner** [comment]
That's not an issue anymore (fixed)
