### ISSUE TITLE
Just updated and nothing works still

### ISSUE THREAD

**Issue by blvckdrxps** [fedddddd/h2-mod#312]
all i get is its an unsupported version but i fully updated it with the, b net installer, i've downloaded everything that necessary, i just keep getting the same thing, i've tried for over 3 days, i'm done with it at this point.

**Comment by V3nilla** [comment]
> all i get is its an unsupported version but i fully updated it with the, b net installer, i've downloaded everything that necessary, i just keep getting the same thing, i've tried for over 3 days, i'm done with it at this point.

Looks like you using cracked version of MW2CR or Latest from Battle.Net, redownload your game using Installation section
