### ISSUE TITLE
Game Has Random Crashes On Takedown Mission

### ISSUE THREAD

**Issue by ITSZYXWASTAKEN** [fedddddd/h2-mod#317]
The Game Just Randomly Crashes And Freezes Apon Clicking Resume Campaign And Takes A Unreasonable Amount Of Time To Unfreeze (this isnt due to my system as i have a rtx 2070 super, and a i7 10700f with the latest graphics drivers) 
![image](https://user-images.githubusercontent.com/78038588/185000007-4f7d472e-1960-4538-97f1-9e9f74f0bf80.png)
[h2-mod-crash-1-2022-08-16-19-00-53.zip](https://github.com/fedddddd/h2-mod/files/9355163/h2-mod-crash-1-2022-08-16-19-00-53.zip)

**Comment by fedddddd** [comment]
It actually is very likely because of your system and specifically your RTX card, both MWR & MW2CR have issues with such cards. Try lowering your graphics and doing what is written under the ["Common Issues" section in the readme](https://github.com/fedddddd/h2-mod#common-issues)

**Comment by ITSZYXWASTAKEN** [comment]
wow thanks, that actually helps, i also played h1 mwr and it had a simillar issue but since this happened later in the campaign i didnt think of this
