### ISSUE TITLE
battle.net installer for mw2cr not working

### ISSUE THREAD

**Issue by Dylan-Matharu** [fedddddd/h2-mod#386]
Error code: blzbntbgsffffff04

I don't have MW2 Campaign Remastered and I was trying to install it toy around with some mods. I followed the instructions from this page: https://github.com/fedddddd/h2-mod

I get the error "Connection to the Blizzard game server has been lost. Please exit and try again." as well as the code stated initially. On the Battle.net client, the play button for MW2CR is greyed out and says "You can't play Call of Duty: MW2 Campaign Remastered yet."

TACT: lazr
UID: lazarus
Locale: enUS

**Comment by fedddddd** [comment]
![image](https://user-images.githubusercontent.com/58637860/201822038-86908abb-1024-4120-aa7e-35aeede9e4de.png)
