### ISSUE TITLE
Don't know what's going on

### ISSUE THREAD

**Issue by PartynJesus** [fedddddd/h2-mod#389]
Mods seem to have loaded properly, but when I load them I still see the Vanilla menu instead of the Spec Ops or Survival menus. I have gotten the Spawner to work but neither of these. I'm now at a dead end and I'm here to see if anyone has any ideas! 

![Screenshot 2022-11-17 013201](https://user-images.githubusercontent.com/118424967/202373417-ef309a13-04b5-45db-87d2-dc1e07c17fe3.png)
![Screenshot 2022-11-17 013232](https://user-images.githubusercontent.com/118424967/202373436-556b1bb0-0a72-4738-a646-29d8248116c9.png)
![Screenshot 2022-11-17 014521](https://user-images.githubusercontent.com/118424967/202375560-2038cd4a-1eb1-4d68-b986-b9081f027a86.png)

**Comment by fedddddd** [comment]
Ask for help in the discord instead of opening pointless issues
