### ISSUE TITLE
how to solove this probleml

### ISSUE THREAD

**Issue by yangyangcilicili** [fedddddd/h2-mod#437]
My h2-mod updated to the latest version 3.0.1, but click in flash back, appear a running box and then did not respond, just update when there are download a series of files, there are also prompts to restart, but after restart did not go in, can not run the game, who can help me solve this problem, please!

**Comment by fedddddd** [comment]
Ask for help in the discord, I can't understand anything you said

**Comment by yangyangcilicili** [comment]
My h2-mod clicked in and flashes back and doesn't enter the game
