### ISSUE TITLE
Split screen coop?

### ISSUE THREAD

**Issue by cleggorz** [fedddddd/h2-mod#449]
Any chance of a split screen coop feature? I imagine the engine doesn't support this but it would be awesome if it was possible.

Actually moving forward from this if that was possible would split screen multiplayer also be possible? I guess not but nostalgia hitting hard rn. Amazing work.

**Comment by fedddddd** [comment]
Possible but not doable, making co-op on its own is already extremely hard, making it split-screen would be even more complicated. The only way anything like MW2CR multiplayer can happen is by porting maps/weapons to h1-mod multiplayer, which has been done, just not released publicly yet.
