### ISSUE TITLE
"Could not create aslr patched binary for MW2CR.exe!  File size mismatch, bad game files" on cracked version

### ISSUE THREAD

**Issue by GarryTale** [fedddddd/h2-mod#454]
im using a cracked version and since i don't understand how to use the way you put in the description, im trying to get it to work on this
but im getting this error (which seems to not be an issue to anyone else in the issue tabs) and its really annoying

**Comment by GarryTale** [comment]
sorry just found out you needed to use the CMD for the command, im dumb
sorry to have bother you 
im now redownloading mw2cr

**Comment by GarryTale** [comment]
hey quick question, why doesn't it work on cracked version? is there a technical reason? (just asking cause im curious)

**Comment by GarryTale** [comment]
Fuck yeah it finally works! after a day of waiting for mw2cr to redownload on battle.net, it works!!

**Comment by GarryTale** [comment]
thanks for making amazing mod :)

**Comment by mjkzy** [comment]
> hey quick question, why doesn't it work on cracked version? is there a technical reason? (just asking cause im curious)

from what i understand, there can be multiple reasons. one reason is that it is just a older version of a game. another reason is because the crack actually has a modified exe (which is the crack) that may interfere with the client. tl;dr just install a clean version and you are good

**Comment by GarryTale** [comment]
alr thx for the awnser !
