### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by AnatolZaitsev** [fedddddd/h2-mod#696]
Restarted game after update in main menu and got this error:

H2-MOD Crash Dump

Version: v3.0.3-57-gbc6c825
Environment: Singleplayer
Timestamp: 2024-07-11-19-26-10
Exception: 0xC0000005
Address: 0x160073DD8
OS Version: 6.2

[h2-mod-crash-1-2024-07-11-19-26-10.zip](https://github.com/user-attachments/files/16180724/h2-mod-crash-1-2024-07-11-19-26-10.zip)

**Comment by AnatolZaitsev** [comment]
redownloaded h2-mod.exe and rejected update in main menu - now it's working

**Comment by fedddddd** [comment]
delete `players2/default/language` or wait for the build to complete and redownload the latest version
