### ISSUE TITLE
Custom Textures Don't Work?

### ISSUE THREAD

**Issue by HaveDex** [fedddddd/h2-mod#711]
Images.cpp mentions custom textures, just like other similar clients (H1, S1x), and there's other mentions of it too like in component_loader, but custom textures don't actually work in-game? Was this feature shelved or is it not fully developed yet?
Dumped textures (any) via Greyhound, put into MW2CR/images doesn't do anything. The structure is right, the format is right, still doesn't work. Shame that you can't replace textures for some reason, would love to be able to chance col and normals for guns, but other stuff too, like in-game posters and such, again similar to H1.

**Comment by fedddddd** [comment]
yes it has been removed. you should use zonetool to modify textures instead, it is the correct method
