### ISSUE TITLE
custom gsc

### ISSUE THREAD

**Issue by Combine900** [fedddddd/h2-mod#91]
Is it possible too load custom gsc files, like we could do with "["https://github.com/momo5502/cod-mod](https://github.com/momo5502/cod-mod)"

I know its a different mod, but would be a cool feature so we could edit the files without restarting or extra injecting.

**Comment by fedddddd** [comment]
That would require a GSC compiler which does exists but isn't complete (is missing functions/token names) so it would be kinda hard to write the scripts. You can instead use the lua scripting API for which there is documentation [here](https://github.com/fedddddd/h2-mod/wiki/Scripting). You can pretty much do anything you would be able to do in GSC while also having extra language features. You can also check out my [survival mod](https://github.com/fedddddd/h2-survival-mod) for more examples.
